# Generated by Django 5.2 on 2025-04-08 17:38

import django.core.validators
import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='brand_images/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EcommerceShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('thumbnail', models.ImageField(upload_to='ecommerce_thumbs/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ecommerce Shop',
                'verbose_name_plural': 'Ecommerce Shops',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('thumbnail', models.ImageField(upload_to='category_thumbs/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('allowed_brands', models.ManyToManyField(blank=True, help_text='Brands that can be associated with this category', related_name='allowed_categories', to='products.brand')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_price_update', models.DateTimeField(blank=True, help_text='When price was last updated', null=True)),
                ('description', django_summernote.fields.SummernoteTextField()),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Key-value pairs of product attributes')),
                ('external_url', models.URLField(help_text='URL to product on the ecommerce site', max_length=500)),
                ('review', models.DecimalField(blank=True, decimal_places=1, help_text='Product rating (0-5 or 0-10 scale)', max_digits=3, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('ecommerce_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.ecommerceshop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['last_price_update'], name='products_pr_last_pr_1a373e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'ecommerce_shop')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['date_recorded'], name='products_pr_date_re_dcd5c4_idx'),
        ),
    ]
